soc/qcom: smcinvoke: Remove qcom's implementation for size_add()
Use size_add() from upstream that has been backported. It resides at
include/linux/overflow.h.
overflow.h header is already included in the headers that are included
at smcinvoke.c such as device.h, slab.h. So, it's unneeded to add overflow.h
explicitly again here. Just remove the size_add() function.

Log:
../drivers/soc/qcom/smcinvoke.c:591:22: error: redefinition of 'size_add'
  591 | static inline size_t size_add(size_t a, size_t b)
      |                      ^~~~~~~~
In file included from ../include/linux/device.h:28,
                 from ../drivers/soc/qcom/smcinvoke.c:11:
../include/linux/overflow.h:273:35: note: previous definition of 'size_add' with type 'size_t(size_t,  size_t)' {aka 'long unsigned int(long unsigned int,  long unsigned int)'}
  273 | static inline size_t __must_check size_add(size_t addend1, size_t addend2)
      |                                   ^~~~~~~~

[TogoFire]: Add log.

Fixes: 1ab137a90eea ("overflow: Implement size_t saturating arithmetic helpers")
Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>
Change-Id: If936bc8dbcb620239f34bc18f45c20acf3deee98
Signed-off-by: TogoFire <togofire@mailfence.com>